import Head from "next/head";
import { ReactNode } from "react";

interface LayoutProps {
  title?: string;
  children: ReactNode;
}

export const Layout = ({ title = "Easy Cleaner", children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-full flex-col">
        <header></header>
        <main className="flex-auto">{children}</main>
        <footer></footer>
      </div>

      <div id="portal" />
    </>
  );
};
